export const SET_GAME_STARTED = "SET_GAME_STARTED";
export const SET_INSTRUCTIONS_EXPANDED = "SET_INSTRUCTIONS_EXPANDED";
export const SET_GUESS = 'SET_GUESS'

export const DECK = {
    FETCH_SUCCESS: 'FETCH_DECK_SUCCESS',
    FETCH_ERROR: 'FETCH_DECK_ERROR',
    DRAW_SUCCESS: 'DRAW_CARD_SUCCESS',
    DRAW_ERROR: 'DRAW_CARD_ERROR'
}